Repository Pavan-Kamthane/C_langauege_, pull requests merged in 2022-10, with the labels that each got.

#6 c program added
  arithmatic.c
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#7 Update README.md
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#8 binary search in c
  bsearch.c
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#14 Pascal's Triangle
  Subhojit Ghosh
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#16 Added C code for bubble sort algorithm
  bubble_sort.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#17 Create Kadane_algorithm.c
  Kadane_algorithm.c
Labels: hacktoberfest-accepted, hacktoberfest

#19 Create Arrays in C
  Arrays in C
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#20 teddy 1404
  teddy1404/factorial.c
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#25 Added selection sort algorithm
  selectionsort.c
Labels: hacktoberfest-accepted, hacktoberfest

#26 Added the Calculator.c
  calculation.c
Labels: hacktoberfest-accepted, hacktoberfest

#27 Updated the README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#28 Create binary_exponentiation.c
  binary_exponentiation.c
Labels: hacktoberfest-accepted, hacktoberfest

#29 romanization_subhagata
  romanization.c
Labels: hacktoberfest-accepted, hacktoberfest

#30 add code for reverse a string
  pabitra0011/Reverse a string.c
Labels: hacktoberfest-accepted, hacktoberfest

#31 added added some simple code of c programming
  2x2MatrixDeterminant.c
  Add Binary Numbers.c
  Print 1 to 100 numbers
  armstrong.c
  string.c
Labels: hacktoberfest-accepted, hacktoberfest

#32 Create Linked_List_Insertions.c
  Linked_List_Insertions.c
Labels: hacktoberfest-accepted, hacktoberfest

#33 vector code added
  vector.c
Labels: hacktoberfest-accepted, hacktoberfest

#34 added to find if char. entered is uppercase or not
  Devansh042005
Labels: hacktoberfest-accepted, hacktoberfest

#39 string length
  string1.c
Labels: hacktoberfest-accepted, hacktoberfest

#37 Create lcs.c
  lcs.c
Labels: hacktoberfest-accepted, hacktoberfest

#38 added my code
  ShaluMishra13
Labels: hacktoberfest-accepted, hacktoberfest

#40 added fibonacci search
  fibonacci_search.c
Labels: hacktoberfest-accepted, hacktoberfest

#41 Convert Decimal Number to Binary Number in C
  Decimal_to_Binary.c
Labels: hacktoberfest-accepted, hacktoberfest

#42 Prime number program in c
  PrimeNumber.c
Labels: hacktoberfest-accepted, hacktoberfest

#44 Create GCD_twonumbers.c
  GCD_twonumbers.c
Labels: hacktoberfest-accepted, hacktoberfest

#45 Organized Files for you sir
  VedantK3/2x2MatrixDeterminant.c
  VedantK3/Add Binary Numbers.c
  VedantK3/Decimal_to_Binary.c
  VedantK3/Fibonacci_Triangle.c
  VedantK3/GCD_twonumbers.c
  VedantK3/Insertion_sort.c
  VedantK3/Kadane_algorithm.c
  VedantK3/Linked_List_Insertions.c
  VedantK3/PrimeNumber.c
  VedantK3/String_again.c
  VedantK3/arithmatic.c
  VedantK3/armstrong.c
  VedantK3/binary_exponentiation.c
  VedantK3/bsearch.c
  VedantK3/bubble_sort.c
  VedantK3/calculation.c
  VedantK3/fibonacci_search.c
  VedantK3/lcs.c
  VedantK3/rock paper.c
  VedantK3/romanization.c
  VedantK3/selectionsort.c
  VedantK3/string.c
  VedantK3/string1.c
  VedantK3/vector.c
Labels: hacktoberfest-accepted, hacktoberfest

#47 hacktoberfest2022
  factorial.c
Labels: hacktoberfest-accepted, hacktoberfest

#48 detect loop in Linked list
  detectLoop.c
Labels: hacktoberfest-accepted, hacktoberfest

#49 HACCKTOBERFEST2022
  C++.CPP321
Labels: hacktoberfest-accepted, hacktoberfest

#50 hacktoberfest2022
  Octal-to-binary.c
Labels: hacktoberfest-accepted, hacktoberfest

#51 Recursive program to Reverse a sentence
  Varunv003/Reversing-sentense-using-recurssion.c
Labels: hacktoberfest-accepted, hacktoberfest

#52 Create Reverse a number
  Reverse a number
Labels: hacktoberfest-accepted, hacktoberfest

#57 Convert uppercase string to lowercase string
  convert.c
Labels: hacktoberfest-accepted, hacktoberfest

#58 Check Armstrong Number of three digits
  Armstrong Number.c
Labels: hacktoberfest-accepted, hacktoberfest

#59 Concatenate Two Strings Without Using strcat()
  Concatenate Two Strings.c
Labels: hacktoberfest-accepted, hacktoberfest

#60 hacktoberfest2022
  powerfunction.c
Labels: hacktoberfest-accepted, hacktoberfest

#56 Create sorting.c
  soting.c
Labels: hacktoberfest-accepted, hacktoberfest

#61 hacktoberfest2022
  dynamic_memory_allocation.c
Labels: hacktoberfest-accepted, hacktoberfest

#63 Added Christmas tree pattern program
  Christmas-tree-pattern-program.c
Labels: hacktoberfest-accepted, hacktoberfest

#62 Simple Program Added
  Sumedh_joshi/TemperatureConverter.c
Labels: hacktoberfest-accepted, hacktoberfest

#64 Delete Stacks
  stacks
Labels: hacktoberfest-accepted, hacktoberfest

#65 Result Calculator
  Sumedh_joshi/Result Calculator
Labels: hacktoberfest-accepted, hacktoberfest

#67 I have added two programs in the file please do check it
  vijayalaxmi23/array.c
  vijayalaxmi23/linkedlist.c
Labels: hacktoberfest-accepted, hacktoberfest

#69 Finding Leap Year
  Sumedh_joshi/Basic Programs
Labels: hacktoberfest-accepted, hacktoberfest

#71 Add two Binary numbers represented as arrays
  addTwoBinaryNumbers.c
Labels: hacktoberfest-accepted, hacktoberfest

#72 Simple Program Distance Converter
  Sumedh_joshi/Distance Converter
  Sumedh_joshi/Program for Leap Year
Labels: hacktoberfest-accepted, hacktoberfest

#74 Simple Programs
  Sumedh_joshi/Mathematical Operations
Labels: hacktoberfest-accepted, hacktoberfest

#76 Added C program.
  binary_search.c
Labels: hacktoberfest-accepted, hacktoberfest

#75 Create warshall.c
  warshall.c
Labels: hacktoberfest-accepted, hacktoberfest

#79 Create area_of_circle.c
  Varun kotgire/area_of_circle.c
Labels: hacktoberfest-accepted, hacktoberfest

#81 added some useful c programs and readme
  ReverseString/Readme.md
  ReverseString/reverse.c
  baseConversion/baseConversion.c
  baseConversion/readme.md
  factorial/fact.c
  factorial/readme.md
  fibonacci/fibonacci.c
  fibonacci/readme.md
  interest/interest.c
  interest/readme.md
  leapYear/leapYear.c
  leapYear/readme.md
  oddOrEven/oddOrEven.c
  oddOrEven/readme.md
  pattern/numberPattern.c
  pattern/readme.md
  postfix/postfix.c
  postfix/readme.md
  primeNumber/primeNumber.c
  primeNumber/readme.md
  wordCount/readme.md
  wordCount/wrdCnt.c
Labels: hacktoberfest-accepted, hacktoberfest

#85 Selection sort in C
  SelectionSort.c
Labels: hacktoberfest-accepted, hacktoberfest

#84 hacktoberfest2022
  Armstrongnumber.c
Labels: hacktoberfest-accepted, hacktoberfest

#83 Created c program addition of two numbers.
  addition.c
Labels: hacktoberfest-accepted, hacktoberfest

#82 Added new file ExponentialSearch
  Exponentialsearch.c
Labels: hacktoberfest-accepted, hacktoberfest

#86 Created a folder for sorting algorithms and add related files to it
  Sorting_in_C/SelectionSort.c
  Sorting_in_C/Shellsort.c
  Sorting_in_C/bubblesort hacktober.c
  Sorting_in_C/insertionSort.c
  Sorting_in_C/mergesort.c
  Sorting_in_C/quicksort.c
Labels: hacktoberfest-accepted, hacktoberfest

#87 Binary Search Algorithm in Recursive and non Recursive mode
  Searching_algorithms_in_C/BinarySearch_Recursive_&_nonRecursive.c
Labels: hacktoberfest-accepted, hacktoberfest

#88 I've added a program to sort element (Merge Sort).
  mergesort.c
Labels: hacktoberfest-accepted, hacktoberfest

#89 added linear search code
  Searching_algorithms_in_C/linear_search.c
Labels: hacktoberfest-accepted, hacktoberfest

#90 Add files via upload
  To add the sum of first and last digits of a number.c
  write a c program to find the sum of  primary diagonal element.c
Labels: hacktoberfest-accepted, hacktoberfest

#92 Create ALLOPP.C
  Ambika/ALLOPP.C
Labels: hacktoberfest-accepted, hacktoberfest

#93 recursion_example.c
  recursion_example.c
Labels: hacktoberfest-accepted, hacktoberfest

#95 Create cosine.c
  cosine.c
Labels: hacktoberfest-accepted, hacktoberfest

#98 polynomial_multiplication
  polynomial_multiplication.c
Labels: hacktoberfest-accepted, hacktoberfest

#97 Create ASSIGN2.C
  ASSIGN2.C
Labels: hacktoberfest-accepted, hacktoberfest

#96 Full Pyramid Pattern using C by Yash Mittal
  full_Pyramid.c
Labels: hacktoberfest-accepted, hacktoberfest

#99 Create Queue in Array.c
  Queue in Array.c
Labels: hacktoberfest-accepted, hacktoberfest

#100 C program to add square of Diagonal in Matrix
  .gitignore
  Array/MultiDimensional/sumOfSquareOfDiagonal.c
Labels: hacktoberfest-accepted, hacktoberfest

#101 Tic Tac Toe Game
  Tic-Tac-Toe/tictactoe.c
Labels: hacktoberfest-accepted, hacktoberfest

#102 Folder Structure updated with relavant files
  C Patterns/Christmas-tree-pattern-program.c
  C Recursion Examples/Fibonacci.c
  C Recursion Examples/Recursion Program
  C Recursion Examples/factorial.c
  C operations/addTwoBinaryNumbers.c
  Searching_algorithms_in_C/binary_search.c
  Sorting_in_C/soting.c
Labels: hacktoberfest-accepted, hacktoberfest

#105 electricitybillgenerator.c
  electricitybillgenerator.c
Labels: hacktoberfest-accepted, hacktoberfest

#104 calculator.c
  calculator.c
Labels: hacktoberfest-accepted, hacktoberfest

#103 arraymultiplication.c
  arraymultiplication.c
Labels: hacktoberfest-accepted, hacktoberfest

#109 Add files via upload
  bubble_sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#108 hacktoberfest2022
  binary_search.c
Labels: hacktoberfest-accepted, hacktoberfest

#122 3 matrix addition
  matrix addition
Labels: hacktoberfest-accepted, hacktoberfest

#121 pattern.c
  pattern.c
Labels: hacktoberfest-accepted, hacktoberfest

#120 Note Exchange
  Note Exchange
Labels: hacktoberfest-accepted, hacktoberfest

#119 Vowelandconsonant.c
  Vowelandconsonant.c
Labels: hacktoberfest-accepted, hacktoberfest

#118 Multiplication.c
  Multiplication.c
Labels: hacktoberfest-accepted, hacktoberfest

#117 Menu driven array program in C language
  array.c
Labels: hacktoberfest-accepted, hacktoberfest

#116 hollowrectangle.cpp
  hollowrectangle.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#123 hacktoberfest2022
  calc.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#115 pascaltriangle.cpp
  C Patterns/pascaltriangle.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#113 palindrome.c
  palindrome.c
Labels: hacktoberfest-accepted, hacktoberfest

#112 yearmonthday.c
  yearmonthday.c
Labels: hacktoberfest-accepted, hacktoberfest

#111 Diamond.c
  C Patterns/Diamond.c
Labels: hacktoberfest-accepted, hacktoberfest

#125 Add files via upload
  area_of_triangle.c
Labels: hacktoberfest-accepted, hacktoberfest

#130 Array Reversal using C by Jatin
  reversealofarray.c
Labels: hacktoberfest-accepted, hacktoberfest

#129 hacktoberfest2022
  C Patterns/StarDiamondpattern.c
Labels: hacktoberfest-accepted, hacktoberfest

#128 Reverse an array
  array_reverse.c
Labels: hacktoberfest-accepted, hacktoberfest

#127 Hacktoberfest2022
  C_lang.cpp
  Sorting.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#132 Insertion Sort
  INSERTION.c
  stack.c
Labels: hacktoberfest-accepted, hacktoberfest

#131 stationery bill
  stationery bill
Labels: hacktoberfest-accepted, hacktoberfest

#124 Hacktoberfest2022
  subhankar/sumCalculation.c
Labels: hacktoberfest-accepted, hacktoberfest

#133 Add atoibase
  baseConversion/atoibase.c
Labels: hacktoberfest-accepted, hacktoberfest

#135 Hacktoberfest2022
  CCode.cpp
Labels: hacktoberfest

#134 delete node at certain position
  linkedList/single/normal/delete_at_nthpos.c
Labels: hacktoberfest-accepted, hacktoberfest

#136 2matrixsum.c
  2matrixsum.c
Labels: hacktoberfest-accepted, hacktoberfest

#137 Rahulr2109 patch 1
  DP application/README.md
  DP application/fibonacci_with_dp.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#107 hacktoberfest2022
  bubble_sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#139 pascaltriangle.cpp
  pascaltriangle.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#138 selection sort
  SelectionSort.c
Labels: hacktoberfest-accepted, hacktoberfest

#140 Added heapsort
  Sorting_in_C/heapsort.c
Labels: hacktoberfest-accepted, hacktoberfest

#141 linked list added
  athul/linkedlist.c
Labels: hacktoberfest-accepted, hacktoberfest

#142 Added radix sort
  Sorting_in_C/radix_sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#143 Create bucket_sort.c
  Sorting_in_C/bucket_sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#144 Added counting sort
  Sorting_in_C/counting_sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#145 Basic C program added
  Basic_C/hello_world.c
Labels: hacktoberfest-accepted, hacktoberfest

#146 Hacktoberfest2022
  Pattern.c
Labels: hacktoberfest-accepted, hacktoberfest

#148 Added Pigeohole sort
  Sorting_in_C/Pigeonhole_Sort.c
Labels: hacktoberfest-accepted, hacktoberfest

#149 Added Towers of Hanoi
  tower_of_hanoi.c
Labels: hacktoberfest-accepted, hacktoberfest

#150 Factorial Of Number.c
  Factorial_Number.c
Labels: hacktoberfest-accepted, hacktoberfest

#151 Added Armstrong Program in c
  Armstrong.c
Labels: hacktoberfest-accepted, hacktoberfest

#153 Create insertionsort.c
  insertionsort.c
Labels: hacktoberfest-accepted, hacktoberfest

#168 Linear_search
  linear_search.c
Labels: hacktoberfest-accepted, hacktoberfest

#167 Create QuickSort.c
  ved142/QuickSort.c
Labels: hacktoberfest-accepted, hacktoberfest

#166 Create multiplication_table.c
  multiplication_table/multiplication_table.c
Labels: hacktoberfest-accepted, hacktoberfest

#165 percentage and average marks calculater of user inputted marks
  Bibek Pant/percentageAndAverageCalculator.c
Labels: hacktoberfest-accepted, hacktoberfest

#164 C Program Basic
  addditio of matrix.c
  addition of even number.c
  addition of odd number.c
  matrix multiplication.c
  quick.c
Labels: hacktoberfest-accepted, hacktoberfest

#163 Create sparse_matrix.c
  disha/Linkedlist.c
  disha/sparse_matrix.c
Labels: hacktoberfest-accepted, hacktoberfest

#162 Calculator.cpp
  Calculator.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#160 reversearray.cpp
  arrayreverse.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#159 Create Hollow rectangle pattern
  Hollow rectangle pattern
Labels: hacktoberfest-accepted, hacktoberfest

#158 arraylinearsearch.cpp
  arraylinearsearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#157 hactoberfest2022
  repeated_elements.c
Labels: hacktoberfest-accepted, hacktoberfest

#155 Create Adding two integers in c
  Adding two integers in c
Labels: hacktoberfest-accepted, hacktoberfest

#154 add tree and quich short
  quich sort.c
  tree.c
Labels: hacktoberfest-accepted, hacktoberfest

#180 Quadraticroots.c
  Quadraticroots.c
Labels: hacktoberfest-accepted, hacktoberfest

#179 ConditionalOperator2.c
  ConditionalOperator2.c
Labels: hacktoberfest-accepted, hacktoberfest

#178 ConditionalOperator1.c
  ConditionalOperator1.c
Labels: hacktoberfest-accepted, hacktoberfest

#177 butterfly.c
  C Patterns/butterfliy.c
Labels: hacktoberfest-accepted, hacktoberfest

#176 Flag.c
  Flag.c
Labels: hacktoberfest-accepted, hacktoberfest

#175 Information_of_C
  Information_of_C
Labels: hacktoberfest-accepted, hacktoberfest

#173 created tower of hanoi program in c
  C Recursion Examples/towerofhanoi.c
  gcd.c
Labels: hacktoberfest-accepted, hacktoberfest

#174 Linked list in c
  AnagramCheck.cpp
  BreakAPalindrome.cpp
  BucketSort.cpp
  CountingSort.cpp
  DNF_sort.cpp
  DayToDate.cpp
  Heap Sort Max Heapify.cpp
  JosephusProblem.cpp
  KMP_algorithm.cpp
  Kadane's_alg.cpp
  LastOccurence.cpp
  LinearSearch.cpp
  LinearSearch_recursion.cpp
  Longest_Common_Subsequence.cpp
  MatrixRotation.cpp
  MatrixTranspose.cpp
  Minimum_Falling_Path_Sum.cpp
  Minimum_Square_Problem.cpp
  NumberIntoEnglishWordClass.cpp
  Reverse_integer.cpp
  SelectionSort.cpp
  SkylineProblem.cpp
  Snake_Ladder_Problem.cpp
  SpiralTraversal.cpp
  Stack.cpp
  TopoSort.cpp
  TowerOfHanoi.cpp
  WaterFlow.cpp
  WaveSort.cpp
  binarySearch.cpp
  binarySearchRecursive.cpp
  bubblesort.cpp
  coin_change_problem.cpp
  countGoodNodesInTree.cpp
  decimaltobinry.cpp
  edit_distance.cpp
  factorial_recursion.cpp
  heapSort.cpp
  insertionsort.cpp
  isPrime.cpp
  iterativeReverseLinklist.cpp
  kclosetElements.cpp
  knapsack_problem.cpp
  kthElementInTheArray.cpp
  levelOrder_binaryTree_traversal.cpp
  linkde.c
  linkedlist_creation
  linkedlist_creation.cpp
  mergesort.cpp
  palindrome-linked-list.cpp
  queneUsingStack.cpp
  quickSort.cpp
  recursiveReverseLinklist.cpp
  searchbst.cpp
  selection sort.cpp
  sort012.cpp
  stackUsingQuene.cpp
  trappingRainWater.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#172 All Operations of Linked list in c
  Linked List/linked_list.c
Labels: hacktoberfest-accepted, hacktoberfest

#171 Create Program to find sum of natural numbers using for loop.c
  Program to find sum of natural numbers using for loop.c
Labels: hacktoberfest-accepted, hacktoberfest

#170 Create infix_postfix.c
  infix_postfix.c
Labels: hacktoberfest-accepted, hacktoberfest

#190 Rainwaterproblemdp.c
  Rainwaterproblemdp.c
Labels: hacktoberfest-accepted, hacktoberfest

#189 hacktoberfest2022
  C operations/addingtwo_octalnumbers.c
Labels: hacktoberfest-accepted, hacktoberfest

#188 freqofno.c
  freqofno.c
Labels: hacktoberfest-accepted, hacktoberfest

#187 TicTacToe.c
  TicTacToe.c
Labels: hacktoberfest-accepted, hacktoberfest

#186 Create Reverse_an_array.c
  Reverse_an_array.c
Labels: hacktoberfest-accepted, hacktoberfest

#185 Added my data
  SS/FindZero.c
  SS/hello_world.c
Labels: hacktoberfest-accepted, hacktoberfest

#184 Palindrome_hacktoberfest
  Palindrome/Palindrome.c
Labels: hacktoberfest-accepted, hacktoberfest

#183 Added 2 programs lcm.c and rotate.c
  lcm.c
  rotate.c
Labels: hacktoberfest-accepted, hacktoberfest

#182 Create pattern_using_C.c
  pattern_using_C.c
Labels: hacktoberfest-accepted, hacktoberfest

#191 Create Circle_Rainbow.c
  Circle_Rainbow.c
Labels: hacktoberfest-accepted, hacktoberfest

#192 Create Happy 😊
  Happy 😊
Labels: hacktoberfest-accepted, hacktoberfest
